<?php
$data = array (
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '眼镜',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 5,
    'level' => 0,
    'id' => '1',
    'name' => '眼镜',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '太阳镜',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '54',
    'level' => 1,
    'id' => '2',
    'name' => '太阳镜',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '光学镜',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '19',
    'level' => 1,
    'id' => '3',
    'name' => '光学镜',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 0,
    'id' => '4',
    'name' => '其他',
  ),
);
?>